version: "3.9"

services:
  database:
    image: postgres:15-alpine
    container_name: kunkhmermobile-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: KunKhmerMobile_DB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/kraft-logs
      KAFKA_CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
    volumes:
      - ./kafka-data:/kafka/kraft-logs
    ports:
      - "9092:9092"

  authenticator-service:
    image: ghcr.io/kunsky12/authenticator-service:latest
    container_name: authenticator-service
    restart: always
    ports:
      - "5000:8080"   # host:container port
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PLAYFAB_TITLE_ID: ${PLAYFAB_TITLE_ID}
      PLAYFAB_SECRET_KEY: ${PLAYFAB_SECRET_KEY}   

  transaction-service:
    image: ghcr.io/kunsky12/transaction-service:latest
    restart: always
    build: /home/ubuntu/Transaction-Microservice
    container_name: transaction-service
    ports:
      - "6000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://43.156.3.86:5432/KunKhmerMobile_DB
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PLAYFAB_TITLE_ID: ${PLAYFAB_TITLE_ID}
      PLAYFAB_SECRET_KEY: ${PLAYFAB_SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      WEBSOCKET_URL: ${WEBSOCKET_URL}
    depends_on:
      - database
      - redis
      - kafka

  match-record-service:
    image: match-record-service:latest
    restart: always
    container_name: match-record-service
    ports:
      - "7000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://43.156.3.86:5432/KunKhmerMobile_DB
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      PLAYFAB_TITLE_ID: ${PLAYFAB_TITLE_ID}
      PLAYFAB_SECRET_KEY: ${PLAYFAB_SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - database
      - transaction-service

volumes:
  db_data:
  kafka_data:
